// Purpose: Parse transcript lines, select time windows, evaluate typed axes, quote exact flags, and render replayable reports.
import{readFile,writeFile}from'node:fs/promises';import{dirname,join}from'node:path';import{fileURLToPath}from'node:url';import{estimateCostUsd,estimateTokens}from'./jev-client.mjs';export{createFakeProvider,createJevClient}from'./jev-client.mjs';const ROOT=dirname(dirname(fileURLToPath(import.meta.url)));
export function parseTranscript(text){return String(text).split(/\r?\n/).filter(Boolean).map((raw,index)=>{const m=raw.match(/^(\d{2}:\d{2}:\d{2})\s+(?:([^:]+):\s*)?(.*)$/);if(!m)return{index,time:null,seconds:null,speaker:'unknown',text:raw,raw};const[,time,speaker='unknown',body]=m;const[h,min,s]=time.split(':').map(Number);return{index,time,seconds:h*3600+min*60+s,speaker:speaker.trim()||'unknown',text:body,raw}})}
export function slidingWindow(lines,minutes=5){const timed=lines.filter(x=>x.seconds!==null);if(!timed.length)return lines;const end=timed.at(-1).seconds,start=end-minutes*60;return lines.filter(x=>x.seconds===null||x.seconds>=start)}
export function validatePack(pack){if(!pack?.id||!Array.isArray(pack.axes)||!pack.axes.length)throw new TypeError('pack requires id and axes');for(const a of pack.axes)if(!a.id||!a.label||!['score','noul'].includes(a.type)||!a.instructions)throw new TypeError('axis requires id, label, type and instructions');return pack}
export async function loadPack(value='default'){const p=value.includes('/')||value.endsWith('.json')?value:join(ROOT,'packs',`${value}.json`);return validatePack(JSON.parse(await readFile(p,'utf8')))}
function axisQuestion(a,agenda){return{type:a.type,instructions:agenda?`${a.instructions}\nDeclared agenda context: ${agenda}`:a.instructions,...(a.criteria?{criteria:a.criteria}:{})}}
export function estimatePulse(lines,pack,agenda=''){const state=lines.map(x=>x.raw).join('\n'),questions=Object.fromEntries(pack.axes.map(a=>[a.id,axisQuestion(a,agenda)]));const n=estimateTokens({state,questions});return{requests:1,estimatedInputTokens:n,estimatedCostUsd:estimateCostUsd(n)}}
export async function evaluateWindow({lines,pack,provider,agenda=''}){const state=lines.map(x=>x.raw).join('\n');const questions=Object.fromEntries(pack.axes.map(a=>[a.id,axisQuestion(a,agenda)]));const first=await provider({state,questions});const flags={};const extra=[];for(const id of['decision_reached','open_question']){const answer=first.answers[id];if(answer?.type!=='noul'||answer.noul<.5||!lines.length)continue;const criteria=Object.fromEntries(lines.slice(0,255).map(x=>[`l${x.index}`,null]));const response=await provider({state,questions:{[id]:{type:'choice',instructions:`Which exact transcript line best demonstrates ${id.replaceAll('_',' ')}?`,criteria}}});const chosen=Number(response.answers[id].choice.slice(1)),line=lines.find(x=>x.index===chosen);if(line)flags[id]=line;extra.push(response)}const input=first.usage.input_tokens+extra.reduce((n,r)=>n+r.usage.input_tokens,0);return{at:new Date().toISOString(),axes:first.answers,flags,speakerCount:new Set(lines.map(x=>x.speaker)).size,lineCount:lines.length,model:first.model,usage:{input_tokens:input,estimated_cost_usd:estimateCostUsd(input)}}}
export function createEvaluator({pack,provider,agenda='',windowMinutes=5}={}){let version=0,lastVersion=-1,lines=[];return{ingest(text){const parsed=parseTranscript(text).map((x,i)=>({...x,index:lines.length+i}));lines.push(...parsed);version++;return parsed.length},async tick(){if(version===lastVersion)return null;lastVersion=version;return evaluateWindow({lines:slidingWindow(lines,windowMinutes),pack,provider,agenda})},get lines(){return[...lines]}}}
export function radarPoints(values,{cx=200,cy=200,radius=150}={}){const n=values.length;return values.map((v,i)=>{const a=-Math.PI/2+i*2*Math.PI/n;return{x:cx+Math.cos(a)*radius*v,y:cy+Math.sin(a)*radius*v}})}
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');export function renderReport(saved){const entries=saved.pulses??[saved],last=entries.at(-1)||{axes:{},flags:{}};const values=Object.values(last.axes).map(a=>a.type==='noul'?a.noul:a.score/Math.max(1,Object.keys(a.legend||{}).length-1));const points=radarPoints(values).map(p=>`${p.x},${p.y}`).join(' ');const flags=Object.entries(last.flags||{}).map(([k,l])=>`<li><b>${esc(k)}</b> ${esc(l.time??'')} ${esc(l.speaker)}: ${esc(l.text)}</li>`).join('');return`<!doctype html><html><head><meta charset="utf-8"><title>Meeting Pulse</title><style>body{font:18px system-ui;max-width:800px;margin:50px auto;background:#0b1220;color:#eff6ff}polygon{fill:#38bdf855;stroke:#38bdf8;stroke-width:3}</style></head><body><h1>Meeting Pulse</h1><svg viewBox="0 0 400 400" width="400"><circle cx="200" cy="200" r="150" fill="none" stroke="#334155"/><polygon points="${points}"/></svg><ul>${flags}</ul><p>${last.speakerCount??0} speakers · ${last.lineCount??0} lines (counted in code)</p></body></html>`}
export async function replay(path,out){const saved=JSON.parse(await readFile(path,'utf8'));await writeFile(out,renderReport(saved));return out}
export async function watchFile(path,{evaluator,intervalMs=45_000,onPulse=()=>{}}={}){let previous='',stopped=false;const check=async()=>{const current=await readFile(path,'utf8');if(current!==previous){const added=current.startsWith(previous)?current.slice(previous.length):current;previous=current;if(added.trim())evaluator.ingest(added);const pulse=await evaluator.tick();if(pulse)await onPulse(pulse)}};await check();const timer=setInterval(()=>check().catch(e=>console.error(e.message)),intervalMs);return()=>{stopped=true;clearInterval(timer);return stopped}}
